SAMPLE_RATE = 16000
BUFFER_DURATION = 2.0
BUFFER_SIZE = int(SAMPLE_RATE * BUFFER_DURATION)
CONFIDENCE_THRESHOLD = 0.6
PROCESSING_INTERVAL = 0.15

WEBSOCKET_URL = "ws://localhost:8080"
RTC_PORT = 8081