version: "3.8"
services:
  game-frontend:
    build: ./packages/game-frontend
    depends_on:
      - game-server
    ports:
      - "3000:3000"
    environment:
      - BUN_INSTALL=/usr/local/bin/bun
    volumes:
      - ./packages/game-frontend:/app
      - ./packages/shared:/shared
  game-server:
    build: ./packages/game-server
    env_file:
      - ./packages/game-server/.env
    ports:
      - "4000:4000"
    environment:
      - BUN_INSTALL=/usr/local/bin/bun
    volumes:
      - ./packages/game-server:/app
      - ./packages/shared:/shared
  speech-api:
    build: ./packages/speech-service
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "4001:4001"
    volumes:
      - ./packages/speech-service/src:/app
