services:
  game-frontend:
    build: 
      context: .
      dockerfile: packages/game-frontend/Dockerfile
    depends_on:
      - game-server
    ports:
      - "3000:3000"
    environment:
      - BUN_INSTALL=/usr/local/bin/bun
    networks:
      - game-network
  game-server:
    build: 
      context: .
      dockerfile: packages/game-server/Dockerfile
    env_file:
      - ./packages/game-server/.env
    ports:
      - "8080:8080"
    environment:
      - BUN_INSTALL=/usr/local/bin/bun
    networks:
      - game-network
  speech-service:
    build: 
      context: .
      dockerfile: packages/speech-service/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "4001:4001"
    networks:
      - game-network

networks:
  game-network: 
    driver: bridge
    
  