SAMPLE_RATE = 16000
CHUNK_DURATION = 0.1
BUFFER_DURATION = 2.0
CHUNK_SIZE = int(SAMPLE_RATE * CHUNK_DURATION)
BUFFER_SIZE = int(SAMPLE_RATE * BUFFER_DURATION)
RESET_TIMEOUT = 10.0 
CONFIDENCE_THRESHOLD = 0.6
TARGET_PATTERN_SIZE = 3